### ISSUE TITLE
First Costumer ID has empty Baskets set

### ISSUE THREAD

**Issue by Shereen-Elsayed** [HaojiHu/TIFUKNN#1]
When I use the preprocessing code, the generated Baskets for the first Costumer ID is empty [[-1]]; despite the original dataset, the first user has around 12 Baskets. Is it meant to be empty, or is there a problem?

**Comment by HaojiHu** [comment]
It is some legacy code which is used for representing the start and end symbol of basket sequence. This is useless for the model here.
