### ISSUE TITLE
Is the reported experiment on the paper using the same dataset & train/test split as on github?

### ISSUE THREAD

**Issue by juhuitseng** [HaojiHu/TIFUKNN#2]
Is the reported experiment on the paper using the same dataset & train/test split as on github?
Cause I ran command ` python TIFUKNN.py ./data/Instacart_history.csv ./data/Instacart_future.csv 900 0.9 0.7 0.9 3 10` but got inconsistent results from the paper reported.

[My output]
recall:  0.24572586831510687
NDCG:  0.3308917426465621

[Paper]
recall:  0.3952
NDCG:  0.3825

**Comment by HaojiHu** [comment]
Thanks for letting me know this. I just realize something wrong with my previous commit. I uploaded some old datasets incorrectly. I just update all the data sets. Please check it again.

**Comment by HaojiHu** [comment]
Sorry, I just realize the problem exists in my git tool. It seems even though I have the correct data sets locally but the data sets are cut off in the github. Please let me fix it.

**Comment by HaojiHu** [comment]
Please check it now and let me know if it works.

**Comment by juhuitseng** [comment]
Yes, the results are much closer than expected. Thanks for your help.
