### ISSUE TITLE
nDCG calculation

### ISSUE THREAD

**Issue by h-jumper** [HaojiHu/TIFUKNN#4]
nDCG的计算与我了解的不同。例如，top10推荐，最后取的推荐序列的前10个物品来计算DCG，取最后一个篮子中物品数来计算IDCG。（最后一个篮子物品数不固定）

`def get_NDCG1(groundtruth, pred_rank_list, k):
    count = 0
    dcg = 0
    for pred in pred_rank_list:
        if count >= k:
            break
        if groundtruth[pred] == 1:
            dcg += (1) / math.log2(count + 1 + 1)
        count += 1
    idcg = 0
    num_real_item = np.sum(groundtruth)
    num_item = int(num_real_item)
    for i in range(num_item):
        idcg += (1) / math.log2(i + 1 + 1)
    ndcg = dcg / idcg
    return ndcg`

**Comment by HaojiHu** [comment]
我不是特别理解你说的问题。你是想说预测的个数和ground truth个数不一样是吗？预测的话，这里假设预测的前10个都是相关的，当然这个很可能是过多了，这个指标主要侧重的是预测的数值排序是不是能够让想要的东西排在前面，而不是看有多少个数是准确的。

**Comment by h-jumper** [comment]
假如是top5推荐，最后推荐5个物品，ground truth个数为7个。若5个全中则在您的代码中计算如下：
dcg@5 = 1/log(2) + 1/log(3) + 1/log(4) + 1/log(5) + 1/log(6)
idcg@7 = 1/log(2) + 1/log(3) + 1/log(4) + 1/log(5) + 1/log(6) + 1/log(7) + 1/log(8)
ndcg=dcg@5 / idcg@7 

我不理解在下一个篮子问题中ndcg计算应该如何计算更为合理。如上面列举ndcg=dcg@5 / idcg@7 还是ndcg=dcg@5 / idcg@5。若ground truth为3是时 应该 ndcg=dcg@5 / idcg@3 还是 ndcg=dcg@3 / idcg@3 或 ndcg=dcg@5 / idcg@5。

**Comment by HaojiHu** [comment]
这个细节提的很好。我当时的理解是ground truth都在那可能会更公平一些，因为不同算法的排序可能会不一样。继续你的例子，在top5推荐下，只用idcg@5会忽略一部分ground truth，但是很难确定忽略哪些比较合适，不同算法可能推的部分不一样，所以我还是使用了7来保留所有ground truth。

**Comment by h-jumper** [comment]
非常感谢您解答我的疑问。下一个篮子推荐不同于其他推荐问题，了解到您的想法后我也认为您的计算方式应该是更加公平。再次感谢您的解答。
