### ISSUE TITLE
temporal_decay_sum_history doesn't seems right

### ISSUE THREAD

**Issue by joeapiwit** [HaojiHu/TIFUKNN#6]
Hi @HaojiHu 
Thank you for your amazing work! Really enjoy reading your paper! It was amazing!
I have just spotted some minor errors that may need your clarification.
In TIFUKNN.py line 595 (def evaluate)
it seems like temporal_decay_sum_history_training and temporal_decay_sum_history_chunk both have the same input.

Should the latter be changed to test_chink instead?

Thank you very much in advance!

![image](https://user-images.githubusercontent.com/49015433/161543757-5c338844-65b8-480b-a7ee-821050e170a4.png)

**Comment by HaojiHu** [comment]
training_chunk is only about historical baskets.

**Comment by joeapiwit** [comment]
Thank you very much!
